# Generated by Django 2.2.8 on 2024-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20240301_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='artists', to='awards.Vote'),
        ),
    ]
