# Generated by Django 2.2.8 on 2024-03-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20240303_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artistId',
            field=models.IntegerField(default=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='songLink',
            field=models.CharField(default=False, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='songName',
            field=models.CharField(default=False, max_length=128),
            preserve_default=False,
        ),
    ]
