# Generated by Django 2.2.28 on 2024-03-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20240303_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userId',
        ),
    ]
