# Generated by Django 2.2.28 on 2024-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_remove_userprofile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='votes',
        ),
        migrations.AddField(
            model_name='artist',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
