# Generated by Django 2.2.28 on 2024-03-14 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20240313_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='artist',
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
