# Generated by Django 2.1.5 on 2024-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0010_auto_20240315_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artistId',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop')], max_length=128, unique=True),
        ),
    ]
