# Generated by Django 2.1.5 on 2024-03-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0011_auto_20240315_1248'),
        ('awards', '0009_auto_20240315_1034'),
    ]

    operations = [
    ]
